//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomehanicarskaRadnjaClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutomehanicarskaRadnjaContainer : DbContext
    {
        public AutomehanicarskaRadnjaContainer()
            : base("name=AutomehanicarskaRadnjaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automobil> Automobils { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
        public virtual DbSet<Posao> Posaos { get; set; }
        public virtual DbSet<TehnickiPregled> TehnickiPregleds { get; set; }
        public virtual DbSet<Kvar> Kvars { get; set; }
        public virtual DbSet<Garaza> Garazas { get; set; }
        public virtual DbSet<Materijal> Materijals { get; set; }
        public virtual DbSet<Alat> Alats { get; set; }
        public virtual DbSet<Oprema> Opremas { get; set; }
    }
}
