//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomehanicarskaRadnjaClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TehnickiPregled
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TehnickiPregled()
        {
            this.Posaos = new HashSet<Posao>();
            this.Materijals = new HashSet<Materijal>();
        }
    
        public int TehnickiPregledId { get; set; }
        public System.DateTime DatumIVreme { get; set; }
        public Status Status { get; set; }
        public string Opis { get; set; }
        public int AutomobilAutomobilId { get; set; }
        public int ZaposleniZaposleniId { get; set; }
        public int GarazaGarazaId { get; set; }
    
        public virtual Automobil Automobil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posao> Posaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materijal> Materijals { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
        public virtual Garaza Garaza { get; set; }
    }
}
